// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sunguIntegration.Dal;

#nullable disable

namespace sunguIntegration.Dal.Migrations
{
    [DbContext(typeof(TrendyolContext))]
    [Migration("20230513063325_providerModelAdded")]
    partial class providerModelAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AttributeValueId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomAttributeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrendyolId")
                        .HasColumnType("int");

                    b.Property<int?>("TrendyolProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrendyolProductId");

                    b.ToTable("TrendyolAttributes");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrendyolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrendyolBrands");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("TrendyolCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TrendyolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrendyolCategoryId");

                    b.ToTable("TrendyolCategories");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolDeliveryOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("DeliveryDuration")
                        .HasColumnType("bigint");

                    b.Property<string>("FastDeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrendyolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrendyolDeliveryOptions");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TrendyolId")
                        .HasColumnType("int");

                    b.Property<int?>("TrendyolProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TrendyolProductId");

                    b.ToTable("TrendyolImages");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<long>("CargoCompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryOptionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DimensionalWeight")
                        .HasColumnType("bigint");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductMainId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrendyolId")
                        .HasColumnType("int");

                    b.Property<long>("VatRate")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOptionId");

                    b.ToTable("TrendyolProducts");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrendyolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TrendyolProviders");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolUserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrendyolApi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrendyolSecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrendyolUserInfos");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolAttribute", b =>
                {
                    b.HasOne("sunguIntegration.Dal.Entities.TrendyolProduct", null)
                        .WithMany("Attributes")
                        .HasForeignKey("TrendyolProductId");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolCategory", b =>
                {
                    b.HasOne("sunguIntegration.Dal.Entities.TrendyolCategory", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("TrendyolCategoryId");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolImage", b =>
                {
                    b.HasOne("sunguIntegration.Dal.Entities.TrendyolProduct", null)
                        .WithMany("Images")
                        .HasForeignKey("TrendyolProductId");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolProduct", b =>
                {
                    b.HasOne("sunguIntegration.Dal.Entities.TrendyolDeliveryOption", "DeliveryOption")
                        .WithMany()
                        .HasForeignKey("DeliveryOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryOption");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("sunguIntegration.Dal.Entities.TrendyolProduct", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
